#!/usr/bin/env python3
"""
Update OpenSSF Best Practices badge for Pegasus (project 12241).

Usage:
  python3 bestpractices-update.py --token YOUR_TOKEN [--dry-run]

How to get your token:
  1. Log into https://www.bestpractices.dev with GitHub OAuth
  2. Open DevTools → Network → reload any page
  3. Find a request to bestpractices.dev, look at Request Headers
  4. Copy the value of the 'X-CSRF-Token' header
  5. Also copy the '_session_id' cookie value
  Then run:
    python3 bestpractices-update.py --token CSRF_TOKEN --session SESSION_COOKIE_VALUE

Alternatively, use the bestpractices.dev web UI and mark each criterion manually.
"""

import argparse
import json
import sys
import urllib.request
import urllib.error

PROJECT_ID = 12241
BASE_URL = f"https://www.bestpractices.dev/projects/{PROJECT_ID}.json"

# ── Criteria that Pegasus already meets ───────────────────────────────────────
#
# Each entry: ("field_name", "Met"|"Unmet"|"N/A", "optional justification")
# Only "Met" and "Unmet" change scores. N/A marks non-applicable criteria.
# Criteria left out remain "?" — do not override unless certain.
#
UPDATES = {
    # ── Passing level ─────────────────────────────────────────────────────────

    "homepage_url_status": "Met",
    # Justification: https://github.com/Guipetris/pegasus — README explains
    # what the software does, how to get it (cargo install), and how to use it.

    "report_url_status": "Met",
    # Justification: https://github.com/Guipetris/pegasus/security/advisories/new
    # GitHub private vulnerability reporting is the primary channel; also
    # documented in SECURITY.md.

    # ── Silver: vulnerability management ──────────────────────────────────────

    "vulnerability_response_process_status": "Met",
    # SECURITY.md defines: 48h ack, 7d assessment, 14/30/60d fix SLAs,
    # coordinated disclosure, private reporting channel.

    "vulnerability_report_credit_status": "Met",
    # SECURITY.md Recognition section: reporters credited in advisories unless
    # they prefer anonymity.

    # ── Silver: quality / testing ─────────────────────────────────────────────

    "dco_status": "Met",
    # dco.yml enforces Signed-off-by on all non-dependabot commits. Commits
    # in the repo have Signed-off-by lines.

    "signed_releases_status": "Met",
    # v0.1.0 release includes .intoto.jsonl SLSA provenance attestations for
    # all three platform binaries, generated by actions/attest-build-provenance.
    # Binaries also signed with cosign (keyless) — .bundle files present.

    "documentation_roadmap_status": "Met",
    # README.md "Roadmap" section documents planned features in approximate
    # priority order.

    "code_of_conduct_status": "Met",
    # CODE_OF_CONDUCT.md — Contributor Covenant 2.1.

    "coding_standards_status": "Met",
    # CONTRIBUTING.md documents: cargo fmt required, cargo clippy -D warnings
    # required, no unsafe code. CI enforces all three on every PR.

    "test_policy_mandated_status": "Met",
    # CONTRIBUTING.md: "new functionality must include tests; bug fixes must
    # include a regression test." CI test job enforces this on every PR.

    "code_review_standards_status": "Met",
    # CONTRIBUTING.md "Code Review Standards" section documents review criteria:
    # correctness, scope, tests, policy conventions, safety, CI passage.

    # ── Silver: governance / documentation ────────────────────────────────────

    "governance_status": "Met",
    # GOVERNANCE.md: roles (project lead + contributors), decision making
    # process, release process, contact channels.

    "documentation_architecture_status": "Met",
    # docs/architecture.md: 6-crate dependency graph, key types per crate,
    # security design decisions, integration points.

    "documentation_security_status": "Met",
    # SECURITY.md: reporting channels, SLAs, scope, security practices
    # (forbid(unsafe_code), SHA-256 integrity, rustls, fail-closed design).

    # ── OSPS-LE (Legal) ───────────────────────────────────────────────────────

    "OSPS-LE-01.01_status": "Met",
    # Apache-2.0 LICENSE file at repo root.

    "OSPS-LE-02.01_status": "Met",
    # REUSE-compliant: .reuse/dep5 declares Apache-2.0 for all files.
    # REUSE badge in README confirms compliance.

    "OSPS-LE-02.02_status": "Met",
    # LICENSE file included in source distribution (via git tag / release).

    "OSPS-LE-03.01_status": "Met",
    # DCO (Developer Certificate of Origin) policy documented in CONTRIBUTING.md.

    "OSPS-LE-03.02_status": "Met",
    # dco.yml CI workflow enforces Signed-off-by on all non-dependabot commits.

    # ── OSPS-DO (Documentation) ───────────────────────────────────────────────

    "OSPS-DO-01.01_status": "Met",
    # README.md on GitHub explains what Pegasus is, what it provides, and how
    # to use it as a library (Quick Start section with code examples).

    "OSPS-DO-02.01_status": "Met",
    # CONTRIBUTING.md covers contribution workflow, scope, code standards,
    # Rego policy conventions, review process.

    "OSPS-DO-04.01_status": "Met",
    # CHANGELOG.md uses Keep a Changelog format; Semantic Versioning declared.

    "OSPS-DO-05.01_status": "Met",
    # CHANGELOG.md maintained with release notes.

    "OSPS-DO-06.01_status": "Met",
    # SECURITY.md: reporting channel, SLAs, coordinated disclosure process.

    "OSPS-DO-07.01_status": "Met",
    # CODE_OF_CONDUCT.md — Contributor Covenant 2.1.

    # ── OSPS-GV (Governance) ──────────────────────────────────────────────────

    "OSPS-GV-01.01_status": "Met",
    # GOVERNANCE.md documents project structure and decision-making process.

    "OSPS-GV-01.02_status": "Met",
    # GOVERNANCE.md + CODEOWNERS: roles documented (project lead, contributors).

    "OSPS-GV-02.01_status": "Met",
    # README.md "The Philosophy" section: project vision documented.
    # GOVERNANCE.md describes project purpose.

    "OSPS-GV-03.01_status": "Met",
    # README.md "Roadmap" section: planned features documented in priority order.

    "OSPS-GV-03.02_status": "Met",
    # GitHub Issues: mechanism for feature requests and bug reports.

    "OSPS-GV-04.01_status": "Met",
    # Apache-2.0 LICENSE file.

    # ── OSPS-QA (Quality Assurance) ───────────────────────────────────────────

    "OSPS-QA-01.01_status": "Met",
    # ci.yml: test, clippy, fmt jobs run on every PR and push to main.

    "OSPS-QA-01.02_status": "Met",
    # CI checks are required; PRs cannot merge with failing CI.

    "OSPS-QA-02.01_status": "Met",
    # coverage.yml: cargo-tarpaulin generates coverage, uploaded to Codecov.

    "OSPS-QA-03.01_status": "Met",
    # clippy job in ci.yml: cargo clippy --all-targets -- -D warnings.

    "OSPS-QA-04.01_status": "Met",
    # cargo audit in ci.yml with SARIF output uploaded to GitHub Security.

    "OSPS-QA-04.02_status": "Met",
    # cargo audit SARIF uploaded via github/codeql-action/upload-sarif.

    "OSPS-QA-05.01_status": "Met",
    # Dependabot: weekly cargo and github-actions dependency updates.

    "OSPS-QA-05.02_status": "Met",
    # dependency-review.yml: GitHub dependency review action on PRs.

    "OSPS-QA-06.01_status": "Met",
    # Cargo.toml with explicit dependency declarations.

    "OSPS-QA-06.02_status": "Met",
    # Cargo.lock committed — all transitive dependencies pinned.

    "OSPS-QA-06.03_status": "Met",
    # Cargo.lock ensures reproducible dependency resolution.

    # ── OSPS-SA (Security Assurance) ──────────────────────────────────────────

    "OSPS-SA-01.01_status": "Met",
    # SECURITY.md: private reporting via GitHub Security Advisories.
    # Explicit instruction not to open public issues for vulnerabilities.

    "OSPS-SA-02.01_status": "Met",
    # SECURITY.md: 48h ack, 7d assessment, 14/30/60d fix SLAs by severity.

    # ── OSPS-BR (Build) ───────────────────────────────────────────────────────

    "OSPS-BR-01.01_status": "Met",
    # Source code in GitHub VCS; build via standard cargo toolchain from source.

    "OSPS-BR-01.02_status": "Met",
    # ci.yml: build, test, lint run automatically on every push/PR.

    "OSPS-BR-01.03_status": "Met",
    # CI checks required before merge; failing CI blocks PR merge.

    "OSPS-BR-01.04_status": "Met",
    # README.md Quick Start + CONTRIBUTING.md document build instructions:
    # cargo build, cargo test, cargo clippy, cargo fmt.

    "OSPS-BR-02.01_status": "Met",
    # CHANGELOG.md included in every release (via git tag history).

    "OSPS-BR-02.02_status": "Met",
    # sbom.yml generates CycloneDX JSON SBOM attached to every tagged release.

    "OSPS-BR-03.01_status": "Met",
    # ci.yml documents build environment: ubuntu-latest + stable Rust toolchain.

    "OSPS-BR-03.02_status": "Met",
    # cargo is the standard build tool for Rust projects.

    "OSPS-BR-04.01_status": "Met",
    # Cargo.lock committed — all build dependencies pinned to exact versions.

    "OSPS-BR-05.01_status": "Met",
    # release.yml: actions/attest-build-provenance generates SLSA provenance.
    # .intoto.jsonl files attached to every platform binary in releases.

    "OSPS-BR-06.01_status": "Met",
    # release.yml: cosign sign-blob (keyless) produces .bundle files.
    # .intoto.jsonl provenance provides higher-assurance attestation.

    # ── OSPS-VM (Vulnerability Management) ────────────────────────────────────

    "OSPS-VM-01.01_status": "Met",
    # cargo audit in CI scans for known vulnerabilities in dependencies.
    # Results uploaded as SARIF to GitHub Security Dashboard.

    "OSPS-VM-02.01_status": "Met",
    # GitHub Security Advisories used for vulnerability tracking and private
    # disclosure. Dependabot auto-creates PRs for vulnerable dependencies.

    "OSPS-VM-03.01_status": "Met",
    # SECURITY.md: 14/30/60d patch timelines by severity (Critical/High/Medium).

    # ── OSPS-AC (Access Control) ──────────────────────────────────────────────

    "OSPS-AC-01.01_status": "Met",
    # GitHub requires 2FA for all accounts with repository write access.
    # CONTRIBUTING.md documents 2FA requirement for contributors.

    # ── OSPS-DO additional ────────────────────────────────────────────────────

    "OSPS-DO-03.01_status": "Met",
    # README.md: Quick Start shows how to add as Cargo dependency with git URL.
    # CONTRIBUTING.md: Development Setup with build/test commands.

    "OSPS-DO-03.02_status": "Met",
    # README.md: Quick Start code examples for library integration.
}

JUSTIFICATIONS = {
    "homepage_url_status": "https://github.com/Guipetris/pegasus — README explains what Pegasus is, how to get it (cargo), and how to use it (library Quick Start with code examples).",
    "report_url_status": "https://github.com/Guipetris/pegasus/security/advisories/new — GitHub private vulnerability reporting; documented in SECURITY.md.",
    "signed_releases_status": "v0.1.0 release includes .intoto.jsonl SLSA provenance attestations (actions/attest-build-provenance) and cosign .bundle files for all three platform binaries.",
    "dco_status": "dco.yml CI workflow enforces Signed-off-by on all non-dependabot PR commits. All repository commits have Signed-off-by lines.",
    "code_review_standards_status": "CONTRIBUTING.md 'Code Review Standards' section: correctness, scope boundaries, test requirements, Rego policy conventions, no-unsafe requirement, CI passage.",
    "governance_status": "GOVERNANCE.md: project lead role, contributor role, decision-making process, release process, contact channels.",
    "documentation_architecture_status": "docs/architecture.md: 6-crate dependency graph, key types per crate, security design, integration points, dependency philosophy.",
    "documentation_security_status": "SECURITY.md: reporting channels, SLAs (48h/7d/14d/30d/60d), scope, security practices (forbid(unsafe_code), SHA-256, rustls, fail-closed).",
}


def build_payload():
    payload = {}
    for field, status in UPDATES.items():
        payload[field] = status
    for field, justification in JUSTIFICATIONS.items():
        just_key = field.replace("_status", "_justification")
        payload[just_key] = justification
    return payload


def main():
    parser = argparse.ArgumentParser(description="Update OpenSSF Best Practices badge for Pegasus")
    parser.add_argument("--token", required=False, help="CSRF token from bestpractices.dev")
    parser.add_argument("--session", required=False, help="_session_id cookie value")
    parser.add_argument("--dry-run", action="store_true", help="Show payload without sending")
    args = parser.parse_args()

    payload = build_payload()

    print(f"Project: {PROJECT_ID} (Pegasus)")
    print(f"Criteria to update: {len(UPDATES)}")
    print()

    met = sum(1 for v in UPDATES.values() if v == "Met")
    unmet = sum(1 for v in UPDATES.values() if v == "Unmet")
    print(f"  Met: {met}")
    print(f"  Unmet: {unmet}")
    print()

    if args.dry_run or (not args.token and not args.session):
        print("── DRY RUN ── Payload that would be sent:")
        print(json.dumps(payload, indent=2))
        if not args.dry_run:
            print()
            print("To actually update, provide --token and --session from your browser session.")
            print("See the docstring at the top of this file for instructions.")
        return

    if not args.token or not args.session:
        print("Error: --token and --session are both required to update the badge.")
        print("Run with --dry-run to preview the payload.")
        sys.exit(1)

    data = json.dumps({"project": payload}).encode("utf-8")

    req = urllib.request.Request(
        BASE_URL,
        data=data,
        method="PATCH",
        headers={
            "Content-Type": "application/json",
            "Accept": "application/json",
            "X-CSRF-Token": args.token,
            "Cookie": f"_session_id={args.session}",
            "User-Agent": "pegasus-badge-updater/1.0",
        },
    )

    try:
        with urllib.request.urlopen(req) as resp:
            result = json.loads(resp.read())
            print(f"Updated. New tiered_percentage: {result.get('tiered_percentage')}%")
            print(f"Badge level: {result.get('badge_level')}")
    except urllib.error.HTTPError as e:
        body = e.read().decode()
        print(f"HTTP {e.code}: {e.reason}")
        print(body[:500])
        sys.exit(1)


if __name__ == "__main__":
    main()
